export const Question = [
  {
    Number: 1,
    prompt: "Which HTML tag is used to define an unordered list?",
    optionA: "<ul>",
    optionB: "<ol>",
    optionC: "<li>",
    optionD: "<list>",
    Answer: "optionA",
  },
  {
    Number: 2,
    prompt:
      "Which property is used in CSS to change the background color of an element?",
    optionA: "color",
    optionB: "background-color",
    optionC: "bg-color",
    optionD: "background",
    Answer: "optionB",
  },
  {
    Number: 3,
    prompt: "What is the correct syntax to link an external CSS file in HTML?",
    optionA: "<link rel='stylesheet' href='style.css'>",
    optionB: "<style src='style.css'>",
    optionC: "<css href='style.css'>",
    optionD: "<script src='style.css'>",
    Answer: "optionA",
  },
  {
    Number: 4,
    prompt: "Which HTTP method is used to submit form data in HTML?",
    optionA: "GET",
    optionB: "POST",
    optionC: "PUT",
    optionD: "DELETE",
    Answer: "optionB",
  },
  {
    Number: 5,
    prompt:
      "Which JavaScript method is used to write a message to the console?",
    optionA: "console.write()",
    optionB: "console.log()",
    optionC: "console.print()",
    optionD: "console.message()",
    Answer: "optionB",
  },
  {
    Number: 6,
    prompt: "What does CSS stand for?",
    optionA: "Colorful Style Sheets",
    optionB: "Computer Style Sheets",
    optionC: "Cascading Style Sheets",
    optionD: "Creative Style Sheets",
    Answer: "optionC",
  },
  {
    Number: 7,
    prompt: "Which of the following is used to define a section in HTML?",
    optionA: "<div>",
    optionB: "<section>",
    optionC: "<header>",
    optionD: "<article>",
    Answer: "optionB",
  },
  {
    Number: 8,
    prompt: "What does the 'src' attribute in an HTML tag stand for?",
    optionA: "style resource",
    optionB: "script reference",
    optionC: "source",
    optionD: "section",
    Answer: "optionC",
  },
  {
    Number: 9,
    prompt:
      "Which of the following is used to send data without refreshing the page in JavaScript?",
    optionA: "Fetch API",
    optionB: "JSON",
    optionC: "PHP",
    optionD: "SQL",
    Answer: "optionA",
  },
  {
    Number: 10,
    prompt:
      "Which of the following is the correct way to declare a variable in JavaScript?",
    optionA: "var myVar = 10;",
    optionB: "variable myVar = 10;",
    optionC: "myVar := 10;",
    optionD: "let var = 10;",
    Answer: "optionA",
  },
];
